### ISSUE TITLE
配置文件在哪里加呢？

### ISSUE THREAD

**Issue by iusky** [tyua07/laravel-upload#2]
配置文件在哪里加呢？

**Comment by Jack--Wang** [comment]
config/filesystem.php 里面的 disks数组加上：

'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => 'your-key',
            'secret' => 'your-secret',
            'region' => 'your-region',
            'bucket' => 'your-bucket',
        ],
        'media' =>[
            'driver' => 'local'  ,
            'root' => public_path().'/media',
        ],

        // 七牛、又拍云、oss
        'qiniu' => [
                'driver'        => 'qiniu',
                'domain'        => '',//你的七牛域名
                'access_key'    => '',//AccessKey
                'secret_key'    => '',//SecretKey
                'bucket'        => '',//Bucket名字
                'transport'     => 'http',//如果支持https，请填写https，如果不支持请填写http
        ],
